# Generated by Django 5.2.8 on 2025-11-30 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название платформы')),
                ('description', models.TextField(blank=True, verbose_name='Описание платформы')),
                ('website', models.URLField(blank=True, verbose_name='Сайт платформы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_url',
            field=models.URLField(blank=True, help_text='Ссылка на страницу курса', verbose_name='Ссылка на курс'),
        ),
        migrations.AlterField(
            model_name='course',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='game.platform', verbose_name='Платформа'),
        ),
    ]
