# Generated by Django 5.2.8 on 2025-11-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_course_created_by_course_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='courses', to='game.category', verbose_name='Категории'),
        ),
    ]
